# Minimum age in minutes before a new version is added to the catalog (7 days)
minimumReleaseAge: 10080

blockExoticSubdeps: true

# Allow building specific packages that are not yet published to the registry, It needs to be clarified why this is required.
allowBuilds:
  core-js: false
  esbuild: false
  lmdb: false
  msgpackr-extract: false
  nice-napi: false
